(define(problem pro-Corner-Random)
(:domain corn-Random)
(:init
(not (dectr))
(not (dectl))
(not (dectt))
(dectb)
( = (disr) 2)
( = (disl) 2)
( = (dist) 2)
( = (disb) 2)
)
(:goal(and(=(disr)0)(=(dist)0)))
)