(define(problem pro-Corner-Random)
(:domain corn-Random)
(:init
(not (dectr))
(not (dectl))
(not (dectt))
(dectb)
( = (disr) 1)
( = (disl) 1)
( = (dist) 3)
( = (disb) 1)
)
(:goal(and(=(disr)0)(=(dist)0)))
)