(define(problem pro-visitall-Random)
(:domain visitall-Random)
(:init
(not (visitr))
(not (visitl))
(not (dectr))
(dectl)
(not (dectt))
(not (dectb))
( = (disr) 5)
( = (disb) 4)
( = (disl) 0)
( = (dist) 0)
( = (numr) 0)
)
(:goal(and(=(numr)(+(disb)(dist)))))
)