(define(problem pro-Diagonal-Return-Random)
(:domain Diagonal-Return-Random)
(:init
(not (dectr))
(not (dectl))
(dectt)
(not (dectb))
(not (visitlt))
(not (visitrt))
(not (visitrb))
( = (disr) 2)
( = (disl) 2)
( = (dist) 2)
( = (disb) 2)
( = (startt) 2)
( = (startl) 2)
)
(:goal(and(visitlt)(visitrt)(visitrb)(=(disl)(startl))(=(dist)(startt))))
)