(define(problem pro-Corner-Random)
(:domain corn-Random)
(:init
(not (dectr))
(dectl)
(not (dectt))
(not (dectb))
( = (disr) 3)
( = (disl) 3)
( = (dist) 3)
( = (disb) 3)
)
(:goal(and(=(disr)0)(=(dist)0)))
)