(define(problem pro-Corner-Random)
(:domain corn-R)
(:init
(dectr)
(not (dectl))
(not (dectt))
(not (dectb))
( = (disr) 1)
( = (disl) 1)
( = (dist) 1)
( = (disb) 1)
)
(:goal(and(=(disr)0)(=(dist)0)))
)