(define(problem pro-grid1)
(:domain grid1)
(:init
(not (gotkey))
(not (isopen))
( = (xkey) 1)
( = (xlock) 1)
( = (ylock) 2)
( = (width) 1)
( = (height) 2)
( = (xagt) 0)
( = (yagt) 0)
( = (ykey) 0)
)
(:goal(and(gotkey)(isopen)(=(xagt)0)(=(yagt)(height))))
)