(define(problem childsnack)
(:domain childsnack)
(:init
(atk)
( = (numnb) 2)
( = (numni) 3)
( = (numgb) 3)
( = (numgi) 3)
( = (numnc) 2)
( = (numgc) 3)
( = (numnsk) 0)
( = (numgsk) 0)
( = (numnst) 0)
( = (numgst) 0)
)
(:goal(and(atk)(=(numnc)0)(=(numgc)0)))
)