(define(problem childsnack)
(:domain childsnack)
(:init
(atk)
( = (numnb) 6)
( = (numni) 4)
( = (numgb) 1)
( = (numgi) 1)
( = (numnc) 4)
( = (numgc) 1)
( = (numnsk) 0)
( = (numgsk) 0)
( = (numnst) 0)
( = (numgst) 0)
)
(:goal(and(atk)(=(numnc)0)(=(numgc)0)))
)