(define(problem barman)
(:domain barman)
(:init
(not (holding))
(empty)
(not (containIg1))
(not (containIg2))
(not (containIg3))
(not (containIg4))
(not (containIg5))
(not (containIg6))
(not (containCt))
( = (numg) 1)
( = (numig1) 1)
( = (numig2) 1)
( = (numig3) 1)
( = (numig4) 1)
( = (numig5) 1)
( = (numig6) 1)
( = (numct) 1)
)
(:goal(and(=(numct)0)(empty)(not(holding))))
)