(define(problem pro-Diagonal-Return-Random)
(:domain Diagonal-Return-Random)
(:init
(not (dectr))
(not (dectl))
(not (dectt))
(dectb)
(not (visitlt))
(not (visitrt))
(not (visitrb))
( = (disr) 4)
( = (disl) 4)
( = (dist) 4)
( = (disb) 4)
( = (startt) 4)
( = (startl) 4)
)
(:goal(and(visitlt)(visitrt)(visitrb)(=(disl)(startl))(=(dist)(startt))))
)