(define(problem pro-Diagonal-Return)
(:domain Diagonal-Return)
(:init
(not (dectr))
(not (dectl))
(not (dectt))
(dectb)
(not (visitlt))
(not (visitrt))
(not (visitrb))
( = (disr) 3)
( = (disl) 6)
( = (dist) 3)
( = (disb) 3)
( = (startt) 3)
( = (startl) 6)
)
(:goal(and(visitlt)(visitrt)(visitrb)(=(disl)(startl))(=(dist)(startt))))
)