(define (problem pro-Hall-Random)
        (:domain Hall-Random)
        (:init
            (and
                (not (visitrt))
                (not (visitrb))
                (not (visitlt))
                (not (visitlb))
                (= (disr) 0)
                (>= (disl) 0)
                (>= (dist) 0)
                (>= (disb) 0)
                (= (disl) (startl))
                (= (dist) (startt))
            )
        )
        (:goal (and
                   (visitrt)
                   (visitlt)
                   (visitlb)
                   (visitrb)
                   (= (disl) (startl))
                   (= (dist) (startt))
               )
        )
)