(define(problem pro-Diagonal-Return)
(:domain Diagonal-Return)
(:init
(not (visitlt))
(not (visitrt))
(not (visitrb))
( = (disr) 4)
( = (disl) 2)
( = (dist) 1)
( = (disb) 4)
( = (startt) 1)
( = (startl) 2)
)
(:goal(and(visitlt)(visitrt)(visitrb)(=(disl)(startl))(=(dist)(startt))))
)